### ISSUE TITLE
Nothing shows up in command prompt after I run reddit_bot.py

### ISSUE THREAD

**Issue by andrewcreed** [bobby-b-bot/reddit#5]
As mentioned in my previous issue, after using the fix suggested, the errors no longer show up (which is good!"), however, nothing else shows up either after running reddit_boy.py. Is it meant to? Furthermore, none of my trigger words seem to interest my bot, who would rather remain silent than do as I command.

**Comment by fzanettini** [comment]
This might sound silly, but is the process really being executed, i.e. hanging? Or does the script finish executing quickly without any outputs?

Also, how is your logs configuration file?

**Comment by andrewcreed** [comment]
If I run the script, it just shows the command of executing it, but not much else, but the command prompt remains open. 

My logging-config file contains the following:

```
[loggers]
keys=root,sLogger

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=fileFormatter,consoleFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

[logger_sLogger]
level=DEBUG
handlers=consoleHandler,fileHandler
qualname=sLogger
propagate=0

[handler_consoleHandler]
class=StreamHandler
level=WARNING
formatter=consoleFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=fileFormatter
args=('logfile.log',)

[formatter_fileFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=

[formatter_consoleFormatter]
format=%(levelname)s - %(message)s
datefmt=
```

I have a feeling this may be the problem.

**Comment by fzanettini** [comment]
The consoleHandler, which is a StreamHandler to stdout, has log level as WARNING and most logs in the bot are on level INFO, which would not appear on a WARNING level log. 

Can you try to change that and see if the logs give us any hints?

**Comment by andrewcreed** [comment]
Changing it to DEBUG yielded the following results. 

`INFO - Started Reddit bot
INFO - Running on environment: TEST
INFO - Got subreddit names: bot running on 2 subreddits
INFO - Loaded blocked users list: 2 users
INFO - Instantiated Reddit client
INFO - Got posts that were already replied
`

However, the bot is still not replying to anyone. He's being very anti-social for a bot.

**Comment by fzanettini** [comment]
It's great the logs are now being prompted in std_out!

From the log messages, it seems the Reddit API client is being instantiated correctly and the bot remains in the "listening" state until it fetches a trigger word. I assume there is an issue with the trigger words, can you share your trigger words file and one example when you try to call the bot?

**Comment by andrewcreed** [comment]
[I can give you around eighteen examples of me attempting to summon this dishonorable bot. ](https://www.reddit.com/r/Jared_Leto_Joker/comments/cetrcy/leto/)

This is the triggers file. 

```
[[  
    "leto",
    "jared leto",
    "leto joker"
 ]]

```

**Comment by fzanettini** [comment]
I think the issue is that your triggers file is using a nested list, and thus the check is run on the first list, which only contains the actual list with the keywords, and so it is checking against an "empty" list of triggers.

Can you try and remove one pair of the [ and ] characters in your triggers file as in the [example](https://github.com/bobby-b-bot/utils/blob/master/triggers.json)?

**Comment by andrewcreed** [comment]
I have removed one of the pairs, and it still is not responding. I'm not sure why there was two pairs in the first place.

**Comment by fzanettini** [comment]
It seems the bot remains listening for the trigger words. Is there anything in the blocked_users list?

**Comment by andrewcreed** [comment]
Sorry about the delay in responding.

The blocked_users list is the same as the one provided by you.

**Comment by fzanettini** [comment]
Sorry about the delay as well. It seems this was indeed a bug and now it is solved in the following pull request:

https://github.com/bobby-b-bot/utils/pull/4 

Can you update and retry?

**Comment by andrewcreed** [comment]
Still isn't working, despite the fix. Maybe it isn't meant to be.
